name: 'Poenta Valei'
aka: ''
title: 'POENTA VALEI'
payoff: "Digital e tecnoeogia par veneti"
description: "Digital e tecnoeogia par veneti. El siicon no se magna, ea poenta sì."
lang: it_IT
paginate: 5

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: https://poentavalei.com

# SEO
google_analytics: UA-179187489-1
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/img/poenta-valei-meta.jpg"

# Build settings
lsi: false
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  footnote_backlink: <
#future: false

#Style
sass:
  sass_dir: _sass
  style: compression

# Favicon
touch_icon: "/assets/img/favicon/apple-touch-icon-144x144.png"
favicon: "/assets/img/favicon/favicon.ico"
twitter:
  username: lucacorsato
  card: summary_large_image

# collections:
#  activities:
#    output: true
#  services:
#    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - classifier-reborn

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
